"""
Curated short display names for every ICSA member school, keyed by URL slug.

The slug is extracted from school URLs (e.g. /schools/navy/ → "navy") and
serves as the stable identifier for each school. Used by the parser to
populate school_short on each team, and by the poller to render notification
text.
"""

_MAPPING: dict[str, str] = {
    # Mid-Atlantic
    "american":                     "American",
    "catholic-america":             "Catholic",
    "christopher-newport":          "CNU",
    "colgate":                      "Colgate",
    "columbia":                     "Columbia",
    "cornell":                      "Cornell",
    "drexel":                       "Drexel",
    "fordham":                      "Fordham",
    "george-washington":            "GW",
    "georgetown":                   "Georgetown",
    "hamilton":                     "Hamilton",
    "hampton":                      "Hampton",
    "hobart-william-sm":            "Hobart",
    "indiana-pennsylvan":           "IUP",
    "loyola-college":               "Loyola",
    "mercyhurst-university":        "Mercyhurst",
    "monmouth":                     "Monmouth",
    "ocean-county":                 "Ocean County",
    "old-dominion":                 "ODU",
    "penn-state-behrend":           "PSU Behrend",
    "penn-state":                   "Penn State",
    "princeton":                    "Princeton",
    "queen":                        "Queen's",
    "rochester":                    "RIT",
    "rutgers":                      "Rutgers",
    "st-john":                      "St. John's",
    "st-mary":                      "St. Mary's",
    "stevens":                      "Stevens",
    "ny-maritime":                  "NY Maritime",
    "stony-brook":                  "Stony Brook",
    "syracuse":                     "Syracuse",
    "kings-point":                  "Kings Point",
    "army":                         "Army",
    "navy":                         "Navy",
    "buffalo":                      "Buffalo",
    "delaware":                     "Delaware",
    "maryland":                     "Maryland",
    "maryland-baltimore":           "UMBC",
    "pennsylvania":                 "Penn",
    "pittsburgh":                   "Pitt",
    "rochester-maisa":              "Rochester",
    "toronto":                      "Toronto",
    "virginia":                     "UVA",
    "villanova":                    "Villanova",
    "virginia-tech":                "Virginia Tech",
    "washington-college":           "Washington Col",
    "webb-institute":               "Webb",
    "william-and-mary":             "William & Mary",

    # Great Lakes
    "case-western":                 "Case Western",
    "cleveland-state-university":   "Cleveland State",
    "denison":                      "Denison",
    "grand-valley-state":           "Grand Valley",
    "hillsdale-college":            "Hillsdale",
    "hope":                         "Hope",
    "indiana":                      "Indiana",
    "iowa-state":                   "Iowa State",
    "john-carroll":                 "John Carroll",
    "lake-forest":                  "Lake Forest",
    "marquette":                    "Marquette",
    "miami-university":             "Miami of Ohio",
    "michigan-state":               "Michigan State",
    "michigan-tech":                "Michigan Tech",
    "northern-michigan":            "N. Michigan",
    "northwestern":                 "Northwestern",
    "ohio-state":                   "Ohio State",
    "ohio":                         "Ohio",
    "purdue":                       "Purdue",
    "saginaw-valley":               "Saginaw Valley",
    "st-marys-college":             "Saint Mary's",
    "chicago":                      "Chicago",
    "illinois":                     "Illinois",
    "iowa":                         "Iowa",
    "michigan":                     "Michigan",
    "minnesota":                    "Minnesota",
    "nebraska-lincoln":             "Nebraska",
    "notre-dame":                   "Notre Dame",
    "saint-thomas":                 "St. Thomas",
    "toledo":                       "Toledo",
    "wisconsin":                    "Wisconsin",
    "washington":                   "Wash U",
    "western-michigan":             "W. Michigan",

    # New England
    "amherst":                      "Amherst",
    "babson":                       "Babson",
    "bates":                        "Bates",
    "bentley":                      "Bentley",
    "boston-college":                "BC",
    "boston-university":             "BU",
    "bowdoin":                      "Bowdoin",
    "brandeis":                     "Brandeis",
    "brown":                        "Brown",
    "colby":                        "Colby",
    "connecticut-college":          "Conn College",
    "dartmouth":                    "Dartmouth",
    "fairfield":                    "Fairfield",
    "harvard":                      "Harvard",
    "maine-maritime":               "Maine Maritime",
    "mit":                          "MIT",
    "mass-maritime":                "Mass Maritime",
    "mcgill":                       "McGill",
    "middlebury":                   "Middlebury",
    "northeastern":                 "Northeastern",
    "olin":                         "Olin",
    "roger-williams":               "Roger Williams",
    "sacred-heart":                 "Sacred Heart",
    "salve-regina":                 "Salve Regina",
    "tufts":                        "Tufts",
    "coast-guard":                  "Coast Guard",
    "connecticut":                  "UConn",
    "maine":                        "Maine",
    "mass-amherst":                 "UMass",
    "umass-dartmouth":              "UMass Dartmouth",
    "new-hampshire":                "UNH",
    "rhode-island":                 "URI",
    "vermont":                      "Vermont",
    "wentworth-institute":          "Wentworth",
    "wesleyan":                     "Wesleyan",
    "williams":                     "Williams",
    "worcester-polytech":           "WPI",
    "yale":                         "Yale",

    # Pacific
    "oregon-state":                 "Oregon State",
    "british-columbia":             "UBC",
    "oregon":                       "Oregon",
    "puget-sound":                  "Puget Sound",
    "victoria":                     "Victoria",
    "washington-nwicsa":            "Washington",
    "western-washington":           "W. Washington",

    # Pacific Coast
    "arizona-state":                "Arizona State",
    "cal-poly":                     "Cal Poly",
    "cal-maritime":                 "Cal Maritime",
    "channel-islands":              "CSU CI",
    "monterey-bay":                 "CSUMB",
    "gonzaga":                      "Gonzaga",
    "loyola-marymount":             "LMU",
    "san-diego-state":              "SDSU",
    "santa-barbara-city":           "SBCC",
    "santa-clara":                  "Santa Clara",
    "stanford":                     "Stanford",
    "berkeley":                     "Cal",
    "uc-davis":                     "UC Davis",
    "uc-irvine":                    "UC Irvine",
    "uc-los-angeles":               "UCLA",
    "uc-san-diego":                 "UCSD",
    "uc-santa-barbara":             "UCSB",
    "uc-santa-cruz":                "UC Santa Cruz",
    "hawaii":                       "Hawaii",
    "univ-of-nevada-reno":          "Nevada",
    "san-diego":                    "USD",
    "southern-cal":                 "USC",

    # South Atlantic
    "auburn":                       "Auburn",
    "clemson":                      "Clemson",
    "charleston":                   "Charleston",
    "college-of-coastal-georgia":   "Coastal Georgia",
    "davidson":                     "Davidson",
    "duke":                         "Duke",
    "eckerd":                       "Eckerd",
    "embry-riddle":                 "Embry-Riddle",
    "flagler":                      "Flagler",
    "florida-tech":                 "Florida Tech",
    "fiu":                          "FIU",
    "florida-state":                "Florida State",
    "georgia-tech":                 "Georgia Tech",
    "jacksonville":                 "Jacksonville",
    "north-carolina-state":         "NC State",
    "palm-beach-atlantic":          "PBA",
    "rollins":                      "Rollins",
    "sewanee":                      "Sewanee",
    "stetson":                      "Stetson",
    "citadel":                      "The Citadel",
    "alabama":                      "Alabama",
    "university-of-central-florida": "UCF",
    "florida":                      "Florida",
    "georgia":                      "Georgia",
    "miami":                        "UMiami",
    "north-carolina":               "UNC",
    "unc-wilmington":               "UNCW",
    "south-carolina":               "South Carolina",
    "south-florida":                "USF",
    "tennessee":                    "Tennessee",
    "vanderbilt":                   "Vanderbilt",
    "wake-forest":                  "Wake Forest",

    # South / Central
    "baylor":                       "Baylor",
    "louisiana-tech":               "Louisiana Tech",
    "loyola":                       "Loyola NOLA",
    "rice":                         "Rice",
    "texas-am":                     "Texas A&M",
    "texas-am-christ":              "TAMUCC",
    "texas-am-galveston":           "TAMUG",
    "texas-christian-university":   "TCU",
    "tulane":                       "Tulane",
    "central-oklahoma":             "UCO",
    "kansas":                       "Kansas",
    "ole-miss":                     "Ole Miss",
    "north-texas":                  "North Texas",
    "oklahoma":                     "Oklahoma",
    "south-alabama":                "South Alabama",
    "texas":                        "Texas",
}


def short_name(slug: str) -> str:
    """Return the curated short display name for a school slug.

    Falls back to the slug itself when the school is not in the mapping.
    """
    return _MAPPING.get(slug) or slug
